services:
  postgres:
    image: postgres:15
    container_name: local_postgres
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev1234
      POSTGRES_DB: bizzpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d bizzpass"]
      interval: 3s
      timeout: 5s
      retries: 5

  crm_backend:
    build:
      context: .
      dockerfile: crm_backend/Dockerfile
    container_name: crm_backend
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: bizzpass
      DB_USER: dev
      DB_PASSWORD: dev1234
      CLOUDINARY_CLOUD_NAME: dyi7xoqhy
      CLOUDINARY_API_KEY: 587679965546116
      CLOUDINARY_API_SECRET: SnmyCwCyL1rjiMMGlmOeR7kHttI
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata: